version: "3.9"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
      - ./prisma/data:/var/lib/postgresql/data
    ports:
      - 5432:5432
